version: "3.8"

services:
  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NAME=World
    volumes:
      - .:/app
    command: python app.py
